// Code generated by MockGen. DO NOT EDIT.
// Source: ./http_client.go
//
// Generated by this command:
//
//	mockgen -package mock -source ./http_client.go -destination ./mock/mock_http_client.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockHTTPClient) Delete(url string, headers map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", url, headers)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHTTPClientMockRecorder) Delete(url, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHTTPClient)(nil).Delete), url, headers)
}

// Get mocks base method.
func (m *MockHTTPClient) Get(url string, headers map[string]string) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url, headers)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockHTTPClientMockRecorder) Get(url, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHTTPClient)(nil).Get), url, headers)
}

// HttpForward mocks base method.
func (m *MockHTTPClient) HttpForward(r *http.Request, url, method string) (int, []byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HttpForward", r, url, method)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// HttpForward indicates an expected call of HttpForward.
func (mr *MockHTTPClientMockRecorder) HttpForward(r, url, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HttpForward", reflect.TypeOf((*MockHTTPClient)(nil).HttpForward), r, url, method)
}

// Post mocks base method.
func (m *MockHTTPClient) Post(url string, headers map[string]string, reqParam any) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Post indicates an expected call of Post.
func (mr *MockHTTPClientMockRecorder) Post(url, headers, reqParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTPClient)(nil).Post), url, headers, reqParam)
}

// Put mocks base method.
func (m *MockHTTPClient) Put(url string, headers map[string]string, reqParam any) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Put indicates an expected call of Put.
func (mr *MockHTTPClientMockRecorder) Put(url, headers, reqParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockHTTPClient)(nil).Put), url, headers, reqParam)
}

// StreamPost mocks base method.
func (m *MockHTTPClient) StreamPost(ctx context.Context, url string, headers map[string]string, reqParam any) (chan string, chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamPost", ctx, url, headers, reqParam)
	ret0, _ := ret[0].(chan string)
	ret1, _ := ret[1].(chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StreamPost indicates an expected call of StreamPost.
func (mr *MockHTTPClientMockRecorder) StreamPost(ctx, url, headers, reqParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamPost", reflect.TypeOf((*MockHTTPClient)(nil).StreamPost), ctx, url, headers, reqParam)
}
