// Code generated by MockGen. DO NOT EDIT.
// Source: ./http_client.go
//
// Generated by this command:
//
//	mockgen -destination=./cmpmock/httpClient_mock.go -package=cmpmock -source=./http_client.go
//

// Package cmpmock is a generated GoMock package.
package cmpmock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gclient "github.com/gogf/gf/v2/net/gclient"
	gomock "go.uber.org/mock/gomock"
)

// MockIHttpClient is a mock of IHttpClient interface.
type MockIHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockIHttpClientMockRecorder
	isgomock struct{}
}

// MockIHttpClientMockRecorder is the mock recorder for MockIHttpClient.
type MockIHttpClientMockRecorder struct {
	mock *MockIHttpClient
}

// NewMockIHttpClient creates a new mock instance.
func NewMockIHttpClient(ctrl *gomock.Controller) *MockIHttpClient {
	mock := &MockIHttpClient{ctrl: ctrl}
	mock.recorder = &MockIHttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHttpClient) EXPECT() *MockIHttpClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIHttpClient) Delete(ctx context.Context, url string) (*gclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, url)
	ret0, _ := ret[0].(*gclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIHttpClientMockRecorder) Delete(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIHttpClient)(nil).Delete), ctx, url)
}

// DeleteExpect2xx mocks base method.
func (m *MockIHttpClient) DeleteExpect2xx(ctx context.Context, url string, data ...any) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url}
	for _, a := range data {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteExpect2xx", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpect2xx indicates an expected call of DeleteExpect2xx.
func (mr *MockIHttpClientMockRecorder) DeleteExpect2xx(ctx, url any, data ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url}, data...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).DeleteExpect2xx), varargs...)
}

// DeleteExpect2xxWithQueryParams mocks base method.
func (m *MockIHttpClient) DeleteExpect2xxWithQueryParams(ctx context.Context, url string, queryData any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpect2xxWithQueryParams", ctx, url, queryData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpect2xxWithQueryParams indicates an expected call of DeleteExpect2xxWithQueryParams.
func (mr *MockIHttpClientMockRecorder) DeleteExpect2xxWithQueryParams(ctx, url, queryData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpect2xxWithQueryParams", reflect.TypeOf((*MockIHttpClient)(nil).DeleteExpect2xxWithQueryParams), ctx, url, queryData)
}

// Do mocks base method.
func (m *MockIHttpClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockIHttpClientMockRecorder) Do(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockIHttpClient)(nil).Do), ctx, req)
}

// DoExpect2xx mocks base method.
func (m *MockIHttpClient) DoExpect2xx(ctx context.Context, req *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoExpect2xx", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoExpect2xx indicates an expected call of DoExpect2xx.
func (mr *MockIHttpClientMockRecorder) DoExpect2xx(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).DoExpect2xx), ctx, req)
}

// Get mocks base method.
func (m *MockIHttpClient) Get(ctx context.Context, url string, queryData ...any) (*gclient.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url}
	for _, a := range queryData {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*gclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIHttpClientMockRecorder) Get(ctx, url any, queryData ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url}, queryData...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIHttpClient)(nil).Get), varargs...)
}

// GetClient mocks base method.
func (m *MockIHttpClient) GetClient() *gclient.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(*gclient.Client)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockIHttpClientMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockIHttpClient)(nil).GetClient))
}

// GetExpect2xx mocks base method.
func (m *MockIHttpClient) GetExpect2xx(ctx context.Context, url string, queryData ...any) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url}
	for _, a := range queryData {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetExpect2xx", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpect2xx indicates an expected call of GetExpect2xx.
func (mr *MockIHttpClientMockRecorder) GetExpect2xx(ctx, url any, queryData ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url}, queryData...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).GetExpect2xx), varargs...)
}

// GetExpect2xxByte mocks base method.
func (m *MockIHttpClient) GetExpect2xxByte(ctx context.Context, url string, queryData ...any) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url}
	for _, a := range queryData {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetExpect2xxByte", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpect2xxByte indicates an expected call of GetExpect2xxByte.
func (mr *MockIHttpClientMockRecorder) GetExpect2xxByte(ctx, url any, queryData ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url}, queryData...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpect2xxByte", reflect.TypeOf((*MockIHttpClient)(nil).GetExpect2xxByte), varargs...)
}

// Post mocks base method.
func (m *MockIHttpClient) Post(ctx context.Context, url string, data any) (*gclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, url, data)
	ret0, _ := ret[0].(*gclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockIHttpClientMockRecorder) Post(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockIHttpClient)(nil).Post), ctx, url, data)
}

// PostExpect2xx mocks base method.
func (m *MockIHttpClient) PostExpect2xx(ctx context.Context, url string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostExpect2xx", ctx, url, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostExpect2xx indicates an expected call of PostExpect2xx.
func (mr *MockIHttpClientMockRecorder) PostExpect2xx(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).PostExpect2xx), ctx, url, data)
}

// PostExpect2xxByte mocks base method.
func (m *MockIHttpClient) PostExpect2xxByte(ctx context.Context, url string, data any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostExpect2xxByte", ctx, url, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostExpect2xxByte indicates an expected call of PostExpect2xxByte.
func (mr *MockIHttpClientMockRecorder) PostExpect2xxByte(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostExpect2xxByte", reflect.TypeOf((*MockIHttpClient)(nil).PostExpect2xxByte), ctx, url, data)
}

// PostFormExpect2xx mocks base method.
func (m *MockIHttpClient) PostFormExpect2xx(ctx context.Context, url string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostFormExpect2xx", ctx, url, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostFormExpect2xx indicates an expected call of PostFormExpect2xx.
func (mr *MockIHttpClientMockRecorder) PostFormExpect2xx(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostFormExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).PostFormExpect2xx), ctx, url, data)
}

// PostJSONExpect2xx mocks base method.
func (m *MockIHttpClient) PostJSONExpect2xx(ctx context.Context, url string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostJSONExpect2xx", ctx, url, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostJSONExpect2xx indicates an expected call of PostJSONExpect2xx.
func (mr *MockIHttpClientMockRecorder) PostJSONExpect2xx(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostJSONExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).PostJSONExpect2xx), ctx, url, data)
}

// PostJSONExpect2xxByte mocks base method.
func (m *MockIHttpClient) PostJSONExpect2xxByte(ctx context.Context, url string, data any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostJSONExpect2xxByte", ctx, url, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostJSONExpect2xxByte indicates an expected call of PostJSONExpect2xxByte.
func (mr *MockIHttpClientMockRecorder) PostJSONExpect2xxByte(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostJSONExpect2xxByte", reflect.TypeOf((*MockIHttpClient)(nil).PostJSONExpect2xxByte), ctx, url, data)
}

// Put mocks base method.
func (m *MockIHttpClient) Put(ctx context.Context, url string, data any) (*gclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, url, data)
	ret0, _ := ret[0].(*gclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockIHttpClientMockRecorder) Put(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockIHttpClient)(nil).Put), ctx, url, data)
}

// PutExpect2xx mocks base method.
func (m *MockIHttpClient) PutExpect2xx(ctx context.Context, url string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutExpect2xx", ctx, url, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutExpect2xx indicates an expected call of PutExpect2xx.
func (mr *MockIHttpClientMockRecorder) PutExpect2xx(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).PutExpect2xx), ctx, url, data)
}

// PutJSONExpect2xx mocks base method.
func (m *MockIHttpClient) PutJSONExpect2xx(ctx context.Context, url string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutJSONExpect2xx", ctx, url, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutJSONExpect2xx indicates an expected call of PutJSONExpect2xx.
func (mr *MockIHttpClientMockRecorder) PutJSONExpect2xx(ctx, url, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutJSONExpect2xx", reflect.TypeOf((*MockIHttpClient)(nil).PutJSONExpect2xx), ctx, url, data)
}
