// Code generated by MockGen. DO NOT EDIT.
// Source: ./redis.go
//
// Generated by this command:
//
//	mockgen -source=./redis.go -destination ./cmpmock/redis_mock.go -package cmpmock
//

// Package cmpmock is a generated GoMock package.
package cmpmock

import (
	reflect "reflect"

	redis "github.com/go-redis/redis/v8"
	gomock "go.uber.org/mock/gomock"
)

// MockRedisCmp is a mock of RedisCmp interface.
type MockRedisCmp struct {
	ctrl     *gomock.Controller
	recorder *MockRedisCmpMockRecorder
	isgomock struct{}
}

// MockRedisCmpMockRecorder is the mock recorder for MockRedisCmp.
type MockRedisCmpMockRecorder struct {
	mock *MockRedisCmp
}

// NewMockRedisCmp creates a new mock instance.
func NewMockRedisCmp(ctrl *gomock.Controller) *MockRedisCmp {
	mock := &MockRedisCmp{ctrl: ctrl}
	mock.recorder = &MockRedisCmpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisCmp) EXPECT() *MockRedisCmpMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockRedisCmp) GetClient() redis.UniversalClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(redis.UniversalClient)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockRedisCmpMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockRedisCmp)(nil).GetClient))
}
