namespace: kweaver-ai
env:
  language: en_US.UTF-8
  timezone: Asia/Shanghai
image:
  registry: swr.cn-east-3.myhuaweicloud.com/kweaver-ai

accessAddress:
  host: 192.168.2.213
  port: 80
  scheme: http
  path: /
depServices:



  zookeeper:
    host: 'zookeeper-headless.resource.svc.cluster.local'
    port: 2181
  rds:
    admin_key: 'a3dlYXZlcjo2'
    host: 'mariadb-proton-mariadb.resource.svc.cluster.local'
    hostRead: 'mariadb-proton-mariadb.resource.svc.cluster.local'
    port: 3306
    portRead: 3306
    source_type: internal
    type: MariaDB
    user: 'kweaver'
    password: '6'
    root_password: 'Gr'
    database: 'kweaver'

  class-443:
    ingressClass: 'nginx'
