// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/discover_worker.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/discover_worker.go -destination ../interfaces/mock/mock_discover_worker.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscoverWorker is a mock of DiscoverWorker interface.
type MockDiscoverWorker struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoverWorkerMockRecorder
	isgomock struct{}
}

// MockDiscoverWorkerMockRecorder is the mock recorder for MockDiscoverWorker.
type MockDiscoverWorkerMockRecorder struct {
	mock *MockDiscoverWorker
}

// NewMockDiscoverWorker creates a new mock instance.
func NewMockDiscoverWorker(ctrl *gomock.Controller) *MockDiscoverWorker {
	mock := &MockDiscoverWorker{ctrl: ctrl}
	mock.recorder = &MockDiscoverWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoverWorker) EXPECT() *MockDiscoverWorkerMockRecorder {
	return m.recorder
}

// ProcessTask mocks base method.
func (m *MockDiscoverWorker) ProcessTask(ctx context.Context, event *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockDiscoverWorkerMockRecorder) ProcessTask(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockDiscoverWorker)(nil).ProcessTask), ctx, event)
}

// Run mocks base method.
func (m *MockDiscoverWorker) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockDiscoverWorkerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDiscoverWorker)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockDiscoverWorker) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockDiscoverWorkerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockDiscoverWorker)(nil).Start))
}
