// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/task_handler.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/task_handler.go -destination ../interfaces/mock/mock_task_handler.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskHandler is a mock of TaskHandler interface.
type MockTaskHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTaskHandlerMockRecorder
	isgomock struct{}
}

// MockTaskHandlerMockRecorder is the mock recorder for MockTaskHandler.
type MockTaskHandlerMockRecorder struct {
	mock *MockTaskHandler
}

// NewMockTaskHandler creates a new mock instance.
func NewMockTaskHandler(ctrl *gomock.Controller) *MockTaskHandler {
	mock := &MockTaskHandler{ctrl: ctrl}
	mock.recorder = &MockTaskHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskHandler) EXPECT() *MockTaskHandlerMockRecorder {
	return m.recorder
}

// HandleTask mocks base method.
func (m *MockTaskHandler) HandleTask(ctx context.Context, task *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleTask indicates an expected call of HandleTask.
func (mr *MockTaskHandlerMockRecorder) HandleTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTask", reflect.TypeOf((*MockTaskHandler)(nil).HandleTask), ctx, task)
}
