// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/build_worker_embedding.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/build_worker_embedding.go -destination ../interfaces/mock/mock_build_worker_embedding.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockEmbeddingBuildWorker is a mock of EmbeddingBuildWorker interface.
type MockEmbeddingBuildWorker struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingBuildWorkerMockRecorder
	isgomock struct{}
}

// MockEmbeddingBuildWorkerMockRecorder is the mock recorder for MockEmbeddingBuildWorker.
type MockEmbeddingBuildWorkerMockRecorder struct {
	mock *MockEmbeddingBuildWorker
}

// NewMockEmbeddingBuildWorker creates a new mock instance.
func NewMockEmbeddingBuildWorker(ctrl *gomock.Controller) *MockEmbeddingBuildWorker {
	mock := &MockEmbeddingBuildWorker{ctrl: ctrl}
	mock.recorder = &MockEmbeddingBuildWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingBuildWorker) EXPECT() *MockEmbeddingBuildWorkerMockRecorder {
	return m.recorder
}

// ProcessTask mocks base method.
func (m *MockEmbeddingBuildWorker) ProcessTask(ctx context.Context, event *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockEmbeddingBuildWorkerMockRecorder) ProcessTask(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockEmbeddingBuildWorker)(nil).ProcessTask), ctx, event)
}

// Run mocks base method.
func (m *MockEmbeddingBuildWorker) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockEmbeddingBuildWorkerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockEmbeddingBuildWorker)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockEmbeddingBuildWorker) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockEmbeddingBuildWorkerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEmbeddingBuildWorker)(nil).Start))
}
