// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/build_task.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/build_task.go -destination ../interfaces/mock/mock_build_worker.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces
