// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/build_worker_batch.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/build_worker_batch.go -destination ../interfaces/mock/mock_build_worker_batch.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchBuildWorker is a mock of BatchBuildWorker interface.
type MockBatchBuildWorker struct {
	ctrl     *gomock.Controller
	recorder *MockBatchBuildWorkerMockRecorder
	isgomock struct{}
}

// MockBatchBuildWorkerMockRecorder is the mock recorder for MockBatchBuildWorker.
type MockBatchBuildWorkerMockRecorder struct {
	mock *MockBatchBuildWorker
}

// NewMockBatchBuildWorker creates a new mock instance.
func NewMockBatchBuildWorker(ctrl *gomock.Controller) *MockBatchBuildWorker {
	mock := &MockBatchBuildWorker{ctrl: ctrl}
	mock.recorder = &MockBatchBuildWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchBuildWorker) EXPECT() *MockBatchBuildWorkerMockRecorder {
	return m.recorder
}

// ProcessTask mocks base method.
func (m *MockBatchBuildWorker) ProcessTask(ctx context.Context, event *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockBatchBuildWorkerMockRecorder) ProcessTask(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockBatchBuildWorker)(nil).ProcessTask), ctx, event)
}

// Run mocks base method.
func (m *MockBatchBuildWorker) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockBatchBuildWorkerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockBatchBuildWorker)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockBatchBuildWorker) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockBatchBuildWorkerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBatchBuildWorker)(nil).Start))
}
