// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/build_task_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/build_task_access.go -destination ../interfaces/mock/mock_build_task_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockBuildTaskAccess is a mock of BuildTaskAccess interface.
type MockBuildTaskAccess struct {
	ctrl     *gomock.Controller
	recorder *MockBuildTaskAccessMockRecorder
	isgomock struct{}
}

// MockBuildTaskAccessMockRecorder is the mock recorder for MockBuildTaskAccess.
type MockBuildTaskAccessMockRecorder struct {
	mock *MockBuildTaskAccess
}

// NewMockBuildTaskAccess creates a new mock instance.
func NewMockBuildTaskAccess(ctrl *gomock.Controller) *MockBuildTaskAccess {
	mock := &MockBuildTaskAccess{ctrl: ctrl}
	mock.recorder = &MockBuildTaskAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildTaskAccess) EXPECT() *MockBuildTaskAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBuildTaskAccess) Create(ctx context.Context, buildTask *interfaces.BuildTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, buildTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBuildTaskAccessMockRecorder) Create(ctx, buildTask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBuildTaskAccess)(nil).Create), ctx, buildTask)
}

// Delete mocks base method.
func (m *MockBuildTaskAccess) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBuildTaskAccessMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBuildTaskAccess)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockBuildTaskAccess) GetAll(ctx context.Context, offset, limit int) ([]*interfaces.BuildTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, offset, limit)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockBuildTaskAccessMockRecorder) GetAll(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBuildTaskAccess)(nil).GetAll), ctx, offset, limit)
}

// GetByID mocks base method.
func (m *MockBuildTaskAccess) GetByID(ctx context.Context, id string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBuildTaskAccessMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBuildTaskAccess)(nil).GetByID), ctx, id)
}

// GetByResourceID mocks base method.
func (m *MockBuildTaskAccess) GetByResourceID(ctx context.Context, resourceID string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByResourceID", ctx, resourceID)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByResourceID indicates an expected call of GetByResourceID.
func (mr *MockBuildTaskAccessMockRecorder) GetByResourceID(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByResourceID", reflect.TypeOf((*MockBuildTaskAccess)(nil).GetByResourceID), ctx, resourceID)
}

// GetByCatalogID mocks base method.
func (m *MockBuildTaskAccess) GetByCatalogID(ctx context.Context, catalogID string) ([]*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCatalogID", ctx, catalogID)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCatalogID indicates an expected call of GetByCatalogID.
func (mr *MockBuildTaskAccessMockRecorder) GetByCatalogID(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCatalogID", reflect.TypeOf((*MockBuildTaskAccess)(nil).GetByCatalogID), ctx, catalogID)
}

// GetStatus mocks base method.
func (m *MockBuildTaskAccess) GetStatus(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockBuildTaskAccessMockRecorder) GetStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockBuildTaskAccess)(nil).GetStatus), ctx, id)
}

// GetUncompletedTasks mocks base method.
func (m *MockBuildTaskAccess) GetUncompletedTasks(ctx context.Context, limit int) ([]*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUncompletedTasks", ctx, limit)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUncompletedTasks indicates an expected call of GetUncompletedTasks.
func (mr *MockBuildTaskAccessMockRecorder) GetUncompletedTasks(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUncompletedTasks", reflect.TypeOf((*MockBuildTaskAccess)(nil).GetUncompletedTasks), ctx, limit)
}

// UpdateStatus mocks base method.
func (m *MockBuildTaskAccess) UpdateStatus(ctx context.Context, id string, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockBuildTaskAccessMockRecorder) UpdateStatus(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockBuildTaskAccess)(nil).UpdateStatus), ctx, id, updates)
}
