// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/scheduled_discover_task_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/scheduled_discover_task_access.go -destination ../interfaces/mock/mock_scheduled_discover_task_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockScheduledDiscoverTaskAccess is a mock of ScheduledDiscoverTaskAccess interface.
type MockScheduledDiscoverTaskAccess struct {
	ctrl     *gomock.Controller
	recorder *MockScheduledDiscoverTaskAccessMockRecorder
	isgomock struct{}
}

// MockScheduledDiscoverTaskAccessMockRecorder is the mock recorder for MockScheduledDiscoverTaskAccess.
type MockScheduledDiscoverTaskAccessMockRecorder struct {
	mock *MockScheduledDiscoverTaskAccess
}

// NewMockScheduledDiscoverTaskAccess creates a new mock instance.
func NewMockScheduledDiscoverTaskAccess(ctrl *gomock.Controller) *MockScheduledDiscoverTaskAccess {
	mock := &MockScheduledDiscoverTaskAccess{ctrl: ctrl}
	mock.recorder = &MockScheduledDiscoverTaskAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduledDiscoverTaskAccess) EXPECT() *MockScheduledDiscoverTaskAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScheduledDiscoverTaskAccess) Create(ctx context.Context, task *interfaces.ScheduledDiscoverTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduledDiscoverTaskAccessMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduledDiscoverTaskAccess)(nil).Create), ctx, task)
}

// Delete mocks base method.
func (m *MockScheduledDiscoverTaskAccess) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduledDiscoverTaskAccessMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduledDiscoverTaskAccess)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockScheduledDiscoverTaskAccess) GetByID(ctx context.Context, id string) (*interfaces.ScheduledDiscoverTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.ScheduledDiscoverTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScheduledDiscoverTaskAccessMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScheduledDiscoverTaskAccess)(nil).GetByID), ctx, id)
}

// GetEnabledTasks mocks base method.
func (m *MockScheduledDiscoverTaskAccess) GetEnabledTasks(ctx context.Context) ([]*interfaces.ScheduledDiscoverTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledTasks", ctx)
	ret0, _ := ret[0].([]*interfaces.ScheduledDiscoverTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledTasks indicates an expected call of GetEnabledTasks.
func (mr *MockScheduledDiscoverTaskAccessMockRecorder) GetEnabledTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledTasks", reflect.TypeOf((*MockScheduledDiscoverTaskAccess)(nil).GetEnabledTasks), ctx)
}

// List mocks base method.
func (m *MockScheduledDiscoverTaskAccess) List(ctx context.Context, params interfaces.ScheduledDiscoverTaskQueryParams) ([]*interfaces.ScheduledDiscoverTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.ScheduledDiscoverTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockScheduledDiscoverTaskAccessMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduledDiscoverTaskAccess)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockScheduledDiscoverTaskAccess) Update(ctx context.Context, task *interfaces.ScheduledDiscoverTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScheduledDiscoverTaskAccessMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScheduledDiscoverTaskAccess)(nil).Update), ctx, task)
}

// UpdateLastRun mocks base method.
func (m *MockScheduledDiscoverTaskAccess) UpdateLastRun(ctx context.Context, id string, lastRun int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastRun", ctx, id, lastRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastRun indicates an expected call of UpdateLastRun.
func (mr *MockScheduledDiscoverTaskAccessMockRecorder) UpdateLastRun(ctx, id, lastRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastRun", reflect.TypeOf((*MockScheduledDiscoverTaskAccess)(nil).UpdateLastRun), ctx, id, lastRun)
}
