// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/build_worker_streaming.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/build_worker_streaming.go -destination ../interfaces/mock/mock_build_worker_streaming.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamingBuildWorker is a mock of StreamingBuildWorker interface.
type MockStreamingBuildWorker struct {
	ctrl     *gomock.Controller
	recorder *MockStreamingBuildWorkerMockRecorder
	isgomock struct{}
}

// MockStreamingBuildWorkerMockRecorder is the mock recorder for MockStreamingBuildWorker.
type MockStreamingBuildWorkerMockRecorder struct {
	mock *MockStreamingBuildWorker
}

// NewMockStreamingBuildWorker creates a new mock instance.
func NewMockStreamingBuildWorker(ctrl *gomock.Controller) *MockStreamingBuildWorker {
	mock := &MockStreamingBuildWorker{ctrl: ctrl}
	mock.recorder = &MockStreamingBuildWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamingBuildWorker) EXPECT() *MockStreamingBuildWorkerMockRecorder {
	return m.recorder
}

// ProcessTask mocks base method.
func (m *MockStreamingBuildWorker) ProcessTask(ctx context.Context, event *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockStreamingBuildWorkerMockRecorder) ProcessTask(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockStreamingBuildWorker)(nil).ProcessTask), ctx, event)
}

// Run mocks base method.
func (m *MockStreamingBuildWorker) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockStreamingBuildWorkerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStreamingBuildWorker)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockStreamingBuildWorker) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockStreamingBuildWorkerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStreamingBuildWorker)(nil).Start))
}
