// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/query.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/query.go -destination ../interfaces/mock/mock_query.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockSQLQueryService is a mock of SQLQueryService interface.
type MockSQLQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockSQLQueryServiceMockRecorder
	isgomock struct{}
}

// MockSQLQueryServiceMockRecorder is the mock recorder for MockSQLQueryService.
type MockSQLQueryServiceMockRecorder struct {
	mock *MockSQLQueryService
}

// NewMockSQLQueryService creates a new mock instance.
func NewMockSQLQueryService(ctrl *gomock.Controller) *MockSQLQueryService {
	mock := &MockSQLQueryService{ctrl: ctrl}
	mock.recorder = &MockSQLQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLQueryService) EXPECT() *MockSQLQueryServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSQLQueryService) Execute(ctx context.Context, req *interfaces.SQLQueryRequest) (*interfaces.SQLQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*interfaces.SQLQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSQLQueryServiceMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSQLQueryService)(nil).Execute), ctx, req)
}
