// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/scheduled_discover_task_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/scheduled_discover_task_service.go -destination ../interfaces/mock/mock_scheduled_discover_task_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockScheduledDiscoverTaskService is a mock of ScheduledDiscoverTaskService interface.
type MockScheduledDiscoverTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockScheduledDiscoverTaskServiceMockRecorder
	isgomock struct{}
}

// MockScheduledDiscoverTaskServiceMockRecorder is the mock recorder for MockScheduledDiscoverTaskService.
type MockScheduledDiscoverTaskServiceMockRecorder struct {
	mock *MockScheduledDiscoverTaskService
}

// NewMockScheduledDiscoverTaskService creates a new mock instance.
func NewMockScheduledDiscoverTaskService(ctrl *gomock.Controller) *MockScheduledDiscoverTaskService {
	mock := &MockScheduledDiscoverTaskService{ctrl: ctrl}
	mock.recorder = &MockScheduledDiscoverTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduledDiscoverTaskService) EXPECT() *MockScheduledDiscoverTaskServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScheduledDiscoverTaskService) Create(ctx context.Context, req *interfaces.ScheduledDiscoverTask) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockScheduledDiscoverTaskService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).Delete), ctx, id)
}

// Disable mocks base method.
func (m *MockScheduledDiscoverTaskService) Disable(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) Disable(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).Disable), ctx, id)
}

// Enable mocks base method.
func (m *MockScheduledDiscoverTaskService) Enable(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) Enable(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).Enable), ctx, id)
}

// ExecuteTask mocks base method.
func (m *MockScheduledDiscoverTaskService) ExecuteTask(ctx context.Context, task *interfaces.ScheduledDiscoverTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteTask indicates an expected call of ExecuteTask.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) ExecuteTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTask", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).ExecuteTask), ctx, task)
}

// GetByID mocks base method.
func (m *MockScheduledDiscoverTaskService) GetByID(ctx context.Context, id string) (*interfaces.ScheduledDiscoverTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.ScheduledDiscoverTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).GetByID), ctx, id)
}

// GetEnabledTasks mocks base method.
func (m *MockScheduledDiscoverTaskService) GetEnabledTasks(ctx context.Context) ([]*interfaces.ScheduledDiscoverTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledTasks", ctx)
	ret0, _ := ret[0].([]*interfaces.ScheduledDiscoverTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledTasks indicates an expected call of GetEnabledTasks.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) GetEnabledTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledTasks", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).GetEnabledTasks), ctx)
}

// List mocks base method.
func (m *MockScheduledDiscoverTaskService) List(ctx context.Context, params interfaces.ScheduledDiscoverTaskQueryParams) ([]*interfaces.ScheduledDiscoverTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.ScheduledDiscoverTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockScheduledDiscoverTaskService) Update(ctx context.Context, id string, req *interfaces.ScheduledDiscoverTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).Update), ctx, id, req)
}

// UpdateLastRun mocks base method.
func (m *MockScheduledDiscoverTaskService) UpdateLastRun(ctx context.Context, id string, lastRun int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastRun", ctx, id, lastRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastRun indicates an expected call of UpdateLastRun.
func (mr *MockScheduledDiscoverTaskServiceMockRecorder) UpdateLastRun(ctx, id, lastRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastRun", reflect.TypeOf((*MockScheduledDiscoverTaskService)(nil).UpdateLastRun), ctx, id, lastRun)
}
