// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/logic_view_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/logic_view_service.go -destination ../interfaces/mock/mock_logic_view_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockLogicViewService is a mock of LogicViewService interface.
type MockLogicViewService struct {
	ctrl     *gomock.Controller
	recorder *MockLogicViewServiceMockRecorder
	isgomock struct{}
}

// MockLogicViewServiceMockRecorder is the mock recorder for MockLogicViewService.
type MockLogicViewServiceMockRecorder struct {
	mock *MockLogicViewService
}

// NewMockLogicViewService creates a new mock instance.
func NewMockLogicViewService(ctrl *gomock.Controller) *MockLogicViewService {
	mock := &MockLogicViewService{ctrl: ctrl}
	mock.recorder = &MockLogicViewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogicViewService) EXPECT() *MockLogicViewServiceMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockLogicViewService) Query(ctx context.Context, resource *interfaces.Resource, params *interfaces.ResourceDataQueryParams) ([]map[string]any, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, resource, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockLogicViewServiceMockRecorder) Query(ctx, resource, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockLogicViewService)(nil).Query), ctx, resource, params)
}
