// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/embedding_task.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/embedding_task.go -destination ../interfaces/mock/mock_embedding_worker.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces
