// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/resource_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/resource_service.go -destination ../interfaces/mock/mock_resource_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockResourceService is a mock of ResourceService interface.
type MockResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockResourceServiceMockRecorder
	isgomock struct{}
}

// MockResourceServiceMockRecorder is the mock recorder for MockResourceService.
type MockResourceServiceMockRecorder struct {
	mock *MockResourceService
}

// NewMockResourceService creates a new mock instance.
func NewMockResourceService(ctrl *gomock.Controller) *MockResourceService {
	mock := &MockResourceService{ctrl: ctrl}
	mock.recorder = &MockResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceService) EXPECT() *MockResourceServiceMockRecorder {
	return m.recorder
}

// CheckExistByCategories mocks base method.
func (m *MockResourceService) CheckExistByCategories(ctx context.Context, catalogID string, categories []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByCategories", ctx, catalogID, categories)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByCategories indicates an expected call of CheckExistByCategories.
func (mr *MockResourceServiceMockRecorder) CheckExistByCategories(ctx, catalogID, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByCategories", reflect.TypeOf((*MockResourceService)(nil).CheckExistByCategories), ctx, catalogID, categories)
}

// CheckExistByID mocks base method.
func (m *MockResourceService) CheckExistByID(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByID indicates an expected call of CheckExistByID.
func (mr *MockResourceServiceMockRecorder) CheckExistByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByID", reflect.TypeOf((*MockResourceService)(nil).CheckExistByID), ctx, id)
}

// CheckExistByName mocks base method.
func (m *MockResourceService) CheckExistByName(ctx context.Context, catalogID, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByName", ctx, catalogID, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByName indicates an expected call of CheckExistByName.
func (mr *MockResourceServiceMockRecorder) CheckExistByName(ctx, catalogID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByName", reflect.TypeOf((*MockResourceService)(nil).CheckExistByName), ctx, catalogID, name)
}

// Create mocks base method.
func (m *MockResourceService) Create(ctx context.Context, req *interfaces.ResourceRequest) (*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockResourceServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockResourceService)(nil).Create), ctx, req)
}

// CreateBuildTask mocks base method.
func (m *MockResourceService) CreateBuildTask(ctx context.Context, id string, req *interfaces.BuildTaskRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBuildTask", ctx, id, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBuildTask indicates an expected call of CreateBuildTask.
func (mr *MockResourceServiceMockRecorder) CreateBuildTask(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBuildTask", reflect.TypeOf((*MockResourceService)(nil).CreateBuildTask), ctx, id, req)
}

// DeleteBuildTask mocks base method.
func (m *MockResourceService) DeleteBuildTask(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBuildTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBuildTask indicates an expected call of DeleteBuildTask.
func (mr *MockResourceServiceMockRecorder) DeleteBuildTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBuildTask", reflect.TypeOf((*MockResourceService)(nil).DeleteBuildTask), ctx, taskID)
}

// DeleteByIDs mocks base method.
func (m *MockResourceService) DeleteByIDs(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockResourceServiceMockRecorder) DeleteByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockResourceService)(nil).DeleteByIDs), ctx, ids)
}

// GetBuildTaskByID mocks base method.
func (m *MockResourceService) GetBuildTaskByID(ctx context.Context, id string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildTaskByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildTaskByID indicates an expected call of GetBuildTaskByID.
func (mr *MockResourceServiceMockRecorder) GetBuildTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildTaskByID", reflect.TypeOf((*MockResourceService)(nil).GetBuildTaskByID), ctx, id)
}

// GetBuildTaskByResourceID mocks base method.
func (m *MockResourceService) GetBuildTaskByResourceID(ctx context.Context, resourceID string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildTaskByResourceID", ctx, resourceID)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildTaskByResourceID indicates an expected call of GetBuildTaskByResourceID.
func (mr *MockResourceServiceMockRecorder) GetBuildTaskByResourceID(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildTaskByResourceID", reflect.TypeOf((*MockResourceService)(nil).GetBuildTaskByResourceID), ctx, resourceID)
}

// GetBuildTasks mocks base method.
func (m *MockResourceService) GetBuildTasks(ctx context.Context, offset, limit int) ([]*interfaces.BuildTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildTasks", ctx, offset, limit)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBuildTasks indicates an expected call of GetBuildTasks.
func (mr *MockResourceServiceMockRecorder) GetBuildTasks(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildTasks", reflect.TypeOf((*MockResourceService)(nil).GetBuildTasks), ctx, offset, limit)
}

// GetByCatalogID mocks base method.
func (m *MockResourceService) GetByCatalogID(ctx context.Context, catalogID string) ([]*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCatalogID", ctx, catalogID)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCatalogID indicates an expected call of GetByCatalogID.
func (mr *MockResourceServiceMockRecorder) GetByCatalogID(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCatalogID", reflect.TypeOf((*MockResourceService)(nil).GetByCatalogID), ctx, catalogID)
}

// GetByID mocks base method.
func (m *MockResourceService) GetByID(ctx context.Context, id string) (*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockResourceServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockResourceService)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockResourceService) GetByIDs(ctx context.Context, ids []string) ([]*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockResourceServiceMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockResourceService)(nil).GetByIDs), ctx, ids)
}

// GetByName mocks base method.
func (m *MockResourceService) GetByName(ctx context.Context, catalogID, name string) (*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, catalogID, name)
	ret0, _ := ret[0].(*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockResourceServiceMockRecorder) GetByName(ctx, catalogID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockResourceService)(nil).GetByName), ctx, catalogID, name)
}

// List mocks base method.
func (m *MockResourceService) List(ctx context.Context, params interfaces.ResourcesQueryParams) ([]*interfaces.Resource, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockResourceServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceService)(nil).List), ctx, params)
}

// ListResourceSrcs mocks base method.
func (m *MockResourceService) ListResourceSrcs(ctx context.Context, params interfaces.ListResourcesQueryParams) ([]*interfaces.ListResourceEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourceSrcs", ctx, params)
	ret0, _ := ret[0].([]*interfaces.ListResourceEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListResourceSrcs indicates an expected call of ListResourceSrcs.
func (mr *MockResourceServiceMockRecorder) ListResourceSrcs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceSrcs", reflect.TypeOf((*MockResourceService)(nil).ListResourceSrcs), ctx, params)
}

// Update mocks base method.
func (m *MockResourceService) Update(ctx context.Context, id string, req *interfaces.ResourceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockResourceServiceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourceService)(nil).Update), ctx, id, req)
}

// UpdateBuildTaskStatus mocks base method.
func (m *MockResourceService) UpdateBuildTaskStatus(ctx context.Context, taskID string, req *interfaces.UpdateBuildTaskStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBuildTaskStatus", ctx, taskID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBuildTaskStatus indicates an expected call of UpdateBuildTaskStatus.
func (mr *MockResourceServiceMockRecorder) UpdateBuildTaskStatus(ctx, taskID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBuildTaskStatus", reflect.TypeOf((*MockResourceService)(nil).UpdateBuildTaskStatus), ctx, taskID, req)
}

// UpdateResource mocks base method.
func (m *MockResourceService) UpdateResource(ctx context.Context, resource *interfaces.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResource", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResource indicates an expected call of UpdateResource.
func (mr *MockResourceServiceMockRecorder) UpdateResource(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResource", reflect.TypeOf((*MockResourceService)(nil).UpdateResource), ctx, resource)
}

// UpdateStatus mocks base method.
func (m *MockResourceService) UpdateStatus(ctx context.Context, id, status, statusMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, statusMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockResourceServiceMockRecorder) UpdateStatus(ctx, id, status, statusMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockResourceService)(nil).UpdateStatus), ctx, id, status, statusMessage)
}
