// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/query.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/query.go -destination ../interfaces/mock/mock_query.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockQuerySessionStore is a mock of QuerySessionStore interface.
type MockQuerySessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockQuerySessionStoreMockRecorder
	isgomock struct{}
}

// MockQuerySessionStoreMockRecorder is the mock recorder for MockQuerySessionStore.
type MockQuerySessionStoreMockRecorder struct {
	mock *MockQuerySessionStore
}

// NewMockQuerySessionStore creates a new mock instance.
func NewMockQuerySessionStore(ctrl *gomock.Controller) *MockQuerySessionStore {
	mock := &MockQuerySessionStore{ctrl: ctrl}
	mock.recorder = &MockQuerySessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerySessionStore) EXPECT() *MockQuerySessionStoreMockRecorder {
	return m.recorder
}

// GetCursor mocks base method.
func (m *MockQuerySessionStore) GetCursor(ctx context.Context, queryID string, offset int) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCursor", ctx, queryID, offset)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCursor indicates an expected call of GetCursor.
func (mr *MockQuerySessionStoreMockRecorder) GetCursor(ctx, queryID, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCursor", reflect.TypeOf((*MockQuerySessionStore)(nil).GetCursor), ctx, queryID, offset)
}

// SetCursor mocks base method.
func (m *MockQuerySessionStore) SetCursor(ctx context.Context, queryID string, offset int, cursorEncoded string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCursor", ctx, queryID, offset, cursorEncoded)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCursor indicates an expected call of SetCursor.
func (mr *MockQuerySessionStoreMockRecorder) SetCursor(ctx, queryID, offset, cursorEncoded any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCursor", reflect.TypeOf((*MockQuerySessionStore)(nil).SetCursor), ctx, queryID, offset, cursorEncoded)
}

// Touch mocks base method.
func (m *MockQuerySessionStore) Touch(ctx context.Context, queryID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, queryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockQuerySessionStoreMockRecorder) Touch(ctx, queryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockQuerySessionStore)(nil).Touch), ctx, queryID)
}

// MockSQLQueryService is a mock of SQLQueryService interface.
type MockSQLQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockSQLQueryServiceMockRecorder
	isgomock struct{}
}

// MockSQLQueryServiceMockRecorder is the mock recorder for MockSQLQueryService.
type MockSQLQueryServiceMockRecorder struct {
	mock *MockSQLQueryService
}

// NewMockSQLQueryService creates a new mock instance.
func NewMockSQLQueryService(ctrl *gomock.Controller) *MockSQLQueryService {
	mock := &MockSQLQueryService{ctrl: ctrl}
	mock.recorder = &MockSQLQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLQueryService) EXPECT() *MockSQLQueryServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSQLQueryService) Execute(ctx context.Context, req *interfaces.SQLQueryRequest) (*interfaces.SQLQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*interfaces.SQLQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSQLQueryServiceMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSQLQueryService)(nil).Execute), ctx, req)
}
