// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/discover_schedule_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/discover_schedule_access.go -destination ../interfaces/mock/mock_discover_schedule_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscoverScheduleAccess is a mock of DiscoverScheduleAccess interface.
type MockDiscoverScheduleAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoverScheduleAccessMockRecorder
	isgomock struct{}
}

// MockDiscoverScheduleAccessMockRecorder is the mock recorder for MockDiscoverScheduleAccess.
type MockDiscoverScheduleAccessMockRecorder struct {
	mock *MockDiscoverScheduleAccess
}

// NewMockDiscoverScheduleAccess creates a new mock instance.
func NewMockDiscoverScheduleAccess(ctrl *gomock.Controller) *MockDiscoverScheduleAccess {
	mock := &MockDiscoverScheduleAccess{ctrl: ctrl}
	mock.recorder = &MockDiscoverScheduleAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoverScheduleAccess) EXPECT() *MockDiscoverScheduleAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiscoverScheduleAccess) Create(ctx context.Context, task *interfaces.DiscoverSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDiscoverScheduleAccessMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).Create), ctx, task)
}

// Delete mocks base method.
func (m *MockDiscoverScheduleAccess) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDiscoverScheduleAccessMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDiscoverScheduleAccess) GetByID(ctx context.Context, id string) (*interfaces.DiscoverSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.DiscoverSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDiscoverScheduleAccessMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).GetByID), ctx, id)
}

// GetEnabledTasks mocks base method.
func (m *MockDiscoverScheduleAccess) GetEnabledTasks(ctx context.Context) ([]*interfaces.DiscoverSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledTasks", ctx)
	ret0, _ := ret[0].([]*interfaces.DiscoverSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledTasks indicates an expected call of GetEnabledTasks.
func (mr *MockDiscoverScheduleAccessMockRecorder) GetEnabledTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledTasks", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).GetEnabledTasks), ctx)
}

// List mocks base method.
func (m *MockDiscoverScheduleAccess) List(ctx context.Context, params interfaces.DiscoverScheduleQueryParams) ([]*interfaces.DiscoverSchedule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.DiscoverSchedule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDiscoverScheduleAccessMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockDiscoverScheduleAccess) Update(ctx context.Context, task *interfaces.DiscoverSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDiscoverScheduleAccessMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).Update), ctx, task)
}

// UpdateLastRun mocks base method.
func (m *MockDiscoverScheduleAccess) UpdateLastRun(ctx context.Context, id string, lastRun int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastRun", ctx, id, lastRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastRun indicates an expected call of UpdateLastRun.
func (mr *MockDiscoverScheduleAccessMockRecorder) UpdateLastRun(ctx, id, lastRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastRun", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).UpdateLastRun), ctx, id, lastRun)
}
