// Code generated by MockGen. DO NOT EDIT.
// Source: ./observability_svc.go
//
// Generated by this command:
//
//	mockgen -source=./observability_svc.go -destination=./iportdrivermock/observability_svc.go -package=iportdrivermock
//

// Package iportdrivermock is a generated GoMock package.
package iportdrivermock

import (
	context "context"
	reflect "reflect"

	observabilityreq "github.com/kweaver-ai/kweaver-core/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/observability/req"
	observabilityresp "github.com/kweaver-ai/kweaver-core/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/observability/resp"
	gomock "go.uber.org/mock/gomock"
)

// MockIObservability is a mock of IObservability interface.
type MockIObservability struct {
	ctrl     *gomock.Controller
	recorder *MockIObservabilityMockRecorder
	isgomock struct{}
}

// MockIObservabilityMockRecorder is the mock recorder for MockIObservability.
type MockIObservabilityMockRecorder struct {
	mock *MockIObservability
}

// NewMockIObservability creates a new mock instance.
func NewMockIObservability(ctrl *gomock.Controller) *MockIObservability {
	mock := &MockIObservability{ctrl: ctrl}
	mock.recorder = &MockIObservabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIObservability) EXPECT() *MockIObservabilityMockRecorder {
	return m.recorder
}

// AgentDetail mocks base method.
func (m *MockIObservability) AgentDetail(ctx context.Context, req *observabilityreq.AgentDetailReq) (*observabilityresp.AgentResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentDetail", ctx, req)
	ret0, _ := ret[0].(*observabilityresp.AgentResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentDetail indicates an expected call of AgentDetail.
func (mr *MockIObservabilityMockRecorder) AgentDetail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentDetail", reflect.TypeOf((*MockIObservability)(nil).AgentDetail), ctx, req)
}

// AnalyticsQuery mocks base method.
func (m *MockIObservability) AnalyticsQuery(ctx context.Context, req *observabilityreq.AnalyticsQueryReq) (*observabilityresp.AnalyticsQueryResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyticsQuery", ctx, req)
	ret0, _ := ret[0].(*observabilityresp.AnalyticsQueryResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsQuery indicates an expected call of AnalyticsQuery.
func (mr *MockIObservabilityMockRecorder) AnalyticsQuery(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsQuery", reflect.TypeOf((*MockIObservability)(nil).AnalyticsQuery), ctx, req)
}

// GetSessionCountsByConversationIDs mocks base method.
func (m *MockIObservability) GetSessionCountsByConversationIDs(ctx context.Context, agentID string, conversationIDs []string, startTime, endTime int64, xAccountID, xAccountType string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionCountsByConversationIDs", ctx, agentID, conversationIDs, startTime, endTime, xAccountID, xAccountType)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionCountsByConversationIDs indicates an expected call of GetSessionCountsByConversationIDs.
func (mr *MockIObservabilityMockRecorder) GetSessionCountsByConversationIDs(ctx, agentID, conversationIDs, startTime, endTime, xAccountID, xAccountType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionCountsByConversationIDs", reflect.TypeOf((*MockIObservability)(nil).GetSessionCountsByConversationIDs), ctx, agentID, conversationIDs, startTime, endTime, xAccountID, xAccountType)
}

// RunDetail mocks base method.
func (m *MockIObservability) RunDetail(ctx context.Context, req *observabilityreq.RunDetailReq) (*observabilityresp.RunDetailResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunDetail", ctx, req)
	ret0, _ := ret[0].(*observabilityresp.RunDetailResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunDetail indicates an expected call of RunDetail.
func (mr *MockIObservabilityMockRecorder) RunDetail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunDetail", reflect.TypeOf((*MockIObservability)(nil).RunDetail), ctx, req)
}

// RunList mocks base method.
func (m *MockIObservability) RunList(ctx context.Context, req *observabilityreq.RunListReq) (*observabilityresp.RunListResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunList", ctx, req)
	ret0, _ := ret[0].(*observabilityresp.RunListResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunList indicates an expected call of RunList.
func (mr *MockIObservabilityMockRecorder) RunList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunList", reflect.TypeOf((*MockIObservability)(nil).RunList), ctx, req)
}

// SessionDetail mocks base method.
func (m *MockIObservability) SessionDetail(ctx context.Context, req *observabilityreq.SessionDetailReq) (*observabilityresp.SessionDetailResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionDetail", ctx, req)
	ret0, _ := ret[0].(*observabilityresp.SessionDetailResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionDetail indicates an expected call of SessionDetail.
func (mr *MockIObservabilityMockRecorder) SessionDetail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionDetail", reflect.TypeOf((*MockIObservability)(nil).SessionDetail), ctx, req)
}

// SessionList mocks base method.
func (m *MockIObservability) SessionList(ctx context.Context, req *observabilityreq.SessionListReq) (*observabilityresp.SessionListResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionList", ctx, req)
	ret0, _ := ret[0].(*observabilityresp.SessionListResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionList indicates an expected call of SessionList.
func (mr *MockIObservabilityMockRecorder) SessionList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionList", reflect.TypeOf((*MockIObservability)(nil).SessionList), ctx, req)
}
