SHELL := /bin/bash

.PHONY: category product file-ext-map permission all

category:
	./category.sh

product:
	./product.sh

file-ext-map:
	./file-ext-map.sh

permission:
	./permission.sh

all: category product file-ext-map
