[pytest]
# 过滤指定类型的警告
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning

python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -s -v
log_cli = false
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S