SHELL := /bin/bash

.PHONY: list-published create get publish unpublish delete flow

list-published:
	./list-published.sh

create:
	./create.sh

get:
	./get.sh

publish:
	./publish.sh

unpublish:
	./unpublish.sh

delete:
	./delete.sh

flow:
	./flow.sh
