// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/bkn_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/bkn_service.go -destination ../interfaces/mock/mock_bkn_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBKNService is a mock of BKNService interface.
type MockBKNService struct {
	ctrl     *gomock.Controller
	recorder *MockBKNServiceMockRecorder
	isgomock struct{}
}

// MockBKNServiceMockRecorder is the mock recorder for MockBKNService.
type MockBKNServiceMockRecorder struct {
	mock *MockBKNService
}

// NewMockBKNService creates a new mock instance.
func NewMockBKNService(ctrl *gomock.Controller) *MockBKNService {
	mock := &MockBKNService{ctrl: ctrl}
	mock.recorder = &MockBKNServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBKNService) EXPECT() *MockBKNServiceMockRecorder {
	return m.recorder
}

// ExportToTar mocks base method.
func (m *MockBKNService) ExportToTar(ctx context.Context, knID, branch string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportToTar", ctx, knID, branch)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportToTar indicates an expected call of ExportToTar.
func (mr *MockBKNServiceMockRecorder) ExportToTar(ctx, knID, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportToTar", reflect.TypeOf((*MockBKNService)(nil).ExportToTar), ctx, knID, branch)
}
