// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/business_system_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/business_system_service.go -destination ../interfaces/mock/mock_business_system_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBusinessSystemService is a mock of BusinessSystemService interface.
type MockBusinessSystemService struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessSystemServiceMockRecorder
	isgomock struct{}
}

// MockBusinessSystemServiceMockRecorder is the mock recorder for MockBusinessSystemService.
type MockBusinessSystemServiceMockRecorder struct {
	mock *MockBusinessSystemService
}

// NewMockBusinessSystemService creates a new mock instance.
func NewMockBusinessSystemService(ctrl *gomock.Controller) *MockBusinessSystemService {
	mock := &MockBusinessSystemService{ctrl: ctrl}
	mock.recorder = &MockBusinessSystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessSystemService) EXPECT() *MockBusinessSystemServiceMockRecorder {
	return m.recorder
}

// BindResource mocks base method.
func (m *MockBusinessSystemService) BindResource(ctx context.Context, bd_id, rid, rtype string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindResource", ctx, bd_id, rid, rtype)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindResource indicates an expected call of BindResource.
func (mr *MockBusinessSystemServiceMockRecorder) BindResource(ctx, bd_id, rid, rtype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindResource", reflect.TypeOf((*MockBusinessSystemService)(nil).BindResource), ctx, bd_id, rid, rtype)
}

// UnbindResource mocks base method.
func (m *MockBusinessSystemService) UnbindResource(ctx context.Context, bd_id, rid, rtype string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindResource", ctx, bd_id, rid, rtype)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindResource indicates an expected call of UnbindResource.
func (mr *MockBusinessSystemServiceMockRecorder) UnbindResource(ctx, bd_id, rid, rtype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindResource", reflect.TypeOf((*MockBusinessSystemService)(nil).UnbindResource), ctx, bd_id, rid, rtype)
}
