// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/risk_type_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/risk_type_access.go -destination ../interfaces/mock/mock_risk_type_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "bkn-backend/interfaces"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRiskTypeAccess is a mock of RiskTypeAccess interface.
type MockRiskTypeAccess struct {
	ctrl     *gomock.Controller
	recorder *MockRiskTypeAccessMockRecorder
}

// MockRiskTypeAccessMockRecorder is the mock recorder for MockRiskTypeAccess.
type MockRiskTypeAccessMockRecorder struct {
	mock *MockRiskTypeAccess
}

// NewMockRiskTypeAccess creates a new mock instance.
func NewMockRiskTypeAccess(ctrl *gomock.Controller) *MockRiskTypeAccess {
	mock := &MockRiskTypeAccess{ctrl: ctrl}
	mock.recorder = &MockRiskTypeAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRiskTypeAccess) EXPECT() *MockRiskTypeAccessMockRecorder {
	return m.recorder
}

// CheckRiskTypeExistByID mocks base method.
func (m *MockRiskTypeAccess) CheckRiskTypeExistByID(ctx context.Context, knID, branch, rtID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRiskTypeExistByID", ctx, knID, branch, rtID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRiskTypeExistByID indicates an expected call of CheckRiskTypeExistByID.
func (mr *MockRiskTypeAccessMockRecorder) CheckRiskTypeExistByID(ctx, knID, branch, rtID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRiskTypeExistByID", reflect.TypeOf((*MockRiskTypeAccess)(nil).CheckRiskTypeExistByID), ctx, knID, branch, rtID)
}

// CheckRiskTypeExistByName mocks base method.
func (m *MockRiskTypeAccess) CheckRiskTypeExistByName(ctx context.Context, knID, branch, rtName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRiskTypeExistByName", ctx, knID, branch, rtName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRiskTypeExistByName indicates an expected call of CheckRiskTypeExistByName.
func (mr *MockRiskTypeAccessMockRecorder) CheckRiskTypeExistByName(ctx, knID, branch, rtName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRiskTypeExistByName", reflect.TypeOf((*MockRiskTypeAccess)(nil).CheckRiskTypeExistByName), ctx, knID, branch, rtName)
}

// CreateRiskType mocks base method.
func (m *MockRiskTypeAccess) CreateRiskType(ctx context.Context, tx *sql.Tx, riskType *interfaces.RiskType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRiskType", ctx, tx, riskType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRiskType indicates an expected call of CreateRiskType.
func (mr *MockRiskTypeAccessMockRecorder) CreateRiskType(ctx, tx, riskType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRiskType", reflect.TypeOf((*MockRiskTypeAccess)(nil).CreateRiskType), ctx, tx, riskType)
}

// DeleteRiskTypesByIDs mocks base method.
func (m *MockRiskTypeAccess) DeleteRiskTypesByIDs(ctx context.Context, tx *sql.Tx, knID, branch string, rtIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRiskTypesByIDs", ctx, tx, knID, branch, rtIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRiskTypesByIDs indicates an expected call of DeleteRiskTypesByIDs.
func (mr *MockRiskTypeAccessMockRecorder) DeleteRiskTypesByIDs(ctx, tx, knID, branch, rtIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRiskTypesByIDs", reflect.TypeOf((*MockRiskTypeAccess)(nil).DeleteRiskTypesByIDs), ctx, tx, knID, branch, rtIDs)
}

// DeleteRiskTypesByKnID mocks base method.
func (m *MockRiskTypeAccess) DeleteRiskTypesByKnID(ctx context.Context, tx *sql.Tx, knID, branch string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRiskTypesByKnID", ctx, tx, knID, branch)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRiskTypesByKnID indicates an expected call of DeleteRiskTypesByKnID.
func (mr *MockRiskTypeAccessMockRecorder) DeleteRiskTypesByKnID(ctx, tx, knID, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRiskTypesByKnID", reflect.TypeOf((*MockRiskTypeAccess)(nil).DeleteRiskTypesByKnID), ctx, tx, knID, branch)
}

// GetAllRiskTypesByKnID mocks base method.
func (m *MockRiskTypeAccess) GetAllRiskTypesByKnID(ctx context.Context, knID, branch string) ([]*interfaces.RiskType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRiskTypesByKnID", ctx, knID, branch)
	ret0, _ := ret[0].([]*interfaces.RiskType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRiskTypesByKnID indicates an expected call of GetAllRiskTypesByKnID.
func (mr *MockRiskTypeAccessMockRecorder) GetAllRiskTypesByKnID(ctx, knID, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRiskTypesByKnID", reflect.TypeOf((*MockRiskTypeAccess)(nil).GetAllRiskTypesByKnID), ctx, knID, branch)
}

// GetRiskTypesByIDs mocks base method.
func (m *MockRiskTypeAccess) GetRiskTypesByIDs(ctx context.Context, knID, branch string, rtIDs []string) ([]*interfaces.RiskType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRiskTypesByIDs", ctx, knID, branch, rtIDs)
	ret0, _ := ret[0].([]*interfaces.RiskType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRiskTypesByIDs indicates an expected call of GetRiskTypesByIDs.
func (mr *MockRiskTypeAccessMockRecorder) GetRiskTypesByIDs(ctx, knID, branch, rtIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRiskTypesByIDs", reflect.TypeOf((*MockRiskTypeAccess)(nil).GetRiskTypesByIDs), ctx, knID, branch, rtIDs)
}

// GetRiskTypesTotal mocks base method.
func (m *MockRiskTypeAccess) GetRiskTypesTotal(ctx context.Context, query interfaces.RiskTypesQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRiskTypesTotal", ctx, query)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRiskTypesTotal indicates an expected call of GetRiskTypesTotal.
func (mr *MockRiskTypeAccessMockRecorder) GetRiskTypesTotal(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRiskTypesTotal", reflect.TypeOf((*MockRiskTypeAccess)(nil).GetRiskTypesTotal), ctx, query)
}

// ListRiskTypes mocks base method.
func (m *MockRiskTypeAccess) ListRiskTypes(ctx context.Context, query interfaces.RiskTypesQueryParams) ([]*interfaces.RiskType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRiskTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.RiskType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRiskTypes indicates an expected call of ListRiskTypes.
func (mr *MockRiskTypeAccessMockRecorder) ListRiskTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRiskTypes", reflect.TypeOf((*MockRiskTypeAccess)(nil).ListRiskTypes), ctx, query)
}

// UpdateRiskType mocks base method.
func (m *MockRiskTypeAccess) UpdateRiskType(ctx context.Context, tx *sql.Tx, riskType *interfaces.RiskType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRiskType", ctx, tx, riskType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRiskType indicates an expected call of UpdateRiskType.
func (mr *MockRiskTypeAccessMockRecorder) UpdateRiskType(ctx, tx, riskType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRiskType", reflect.TypeOf((*MockRiskTypeAccess)(nil).UpdateRiskType), ctx, tx, riskType)
}
