// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/agent_operator_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/agent_operator_access.go -destination ../interfaces/mock/mock_agent_operator_access.go -package mock_interfaces
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "bkn-backend/interfaces"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAgentOperatorAccess is a mock of AgentOperatorAccess interface.
type MockAgentOperatorAccess struct {
	ctrl     *gomock.Controller
	recorder *MockAgentOperatorAccessMockRecorder
	isgomock struct{}
}

// MockAgentOperatorAccessMockRecorder is the mock recorder for MockAgentOperatorAccess.
type MockAgentOperatorAccessMockRecorder struct {
	mock *MockAgentOperatorAccess
}

// NewMockAgentOperatorAccess creates a new mock instance.
func NewMockAgentOperatorAccess(ctrl *gomock.Controller) *MockAgentOperatorAccess {
	mock := &MockAgentOperatorAccess{ctrl: ctrl}
	mock.recorder = &MockAgentOperatorAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentOperatorAccess) EXPECT() *MockAgentOperatorAccessMockRecorder {
	return m.recorder
}

// GetAgentOperatorByID mocks base method.
func (m *MockAgentOperatorAccess) GetAgentOperatorByID(ctx context.Context, operatorID string) (interfaces.AgentOperator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentOperatorByID", ctx, operatorID)
	ret0, _ := ret[0].(interfaces.AgentOperator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentOperatorByID indicates an expected call of GetAgentOperatorByID.
func (mr *MockAgentOperatorAccessMockRecorder) GetAgentOperatorByID(ctx, operatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentOperatorByID", reflect.TypeOf((*MockAgentOperatorAccess)(nil).GetAgentOperatorByID), ctx, operatorID)
}

// GetMcpToolByName mocks base method.
func (m *MockAgentOperatorAccess) GetMcpToolByName(ctx context.Context, mcpID, toolName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMcpToolByName", ctx, mcpID, toolName)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMcpToolByName indicates an expected call of GetMcpToolByName.
func (mr *MockAgentOperatorAccessMockRecorder) GetMcpToolByName(ctx, mcpID, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMcpToolByName", reflect.TypeOf((*MockAgentOperatorAccess)(nil).GetMcpToolByName), ctx, mcpID, toolName)
}

// GetToolByID mocks base method.
func (m *MockAgentOperatorAccess) GetToolByID(ctx context.Context, boxID, toolID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolByID", ctx, boxID, toolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetToolByID indicates an expected call of GetToolByID.
func (mr *MockAgentOperatorAccessMockRecorder) GetToolByID(ctx, boxID, toolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolByID", reflect.TypeOf((*MockAgentOperatorAccess)(nil).GetToolByID), ctx, boxID, toolID)
}
