// Code generated by MockGen. DO NOT EDIT.
// Source: ./session_redis.go
//
// Generated by this command:
//
//	mockgen -source=./session_redis.go -destination ./isessionredismock/session_redis.go -package isessionredismock
//

// Package isessionredismock is a generated GoMock package.
package isessionredismock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISessionRedisAcc is a mock of ISessionRedisAcc interface.
type MockISessionRedisAcc struct {
	ctrl     *gomock.Controller
	recorder *MockISessionRedisAccMockRecorder
	isgomock struct{}
}

// MockISessionRedisAccMockRecorder is the mock recorder for MockISessionRedisAcc.
type MockISessionRedisAccMockRecorder struct {
	mock *MockISessionRedisAcc
}

// NewMockISessionRedisAcc creates a new mock instance.
func NewMockISessionRedisAcc(ctrl *gomock.Controller) *MockISessionRedisAcc {
	mock := &MockISessionRedisAcc{ctrl: ctrl}
	mock.recorder = &MockISessionRedisAccMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionRedisAcc) EXPECT() *MockISessionRedisAccMockRecorder {
	return m.recorder
}

// GetSession mocks base method.
func (m *MockISessionRedisAcc) GetSession(ctx context.Context, conversationID string) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, conversationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSession indicates an expected call of GetSession.
func (mr *MockISessionRedisAccMockRecorder) GetSession(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockISessionRedisAcc)(nil).GetSession), ctx, conversationID)
}

// GetSessionTTL mocks base method.
func (m *MockISessionRedisAcc) GetSessionTTL(ctx context.Context, conversationID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionTTL", ctx, conversationID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionTTL indicates an expected call of GetSessionTTL.
func (mr *MockISessionRedisAccMockRecorder) GetSessionTTL(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionTTL", reflect.TypeOf((*MockISessionRedisAcc)(nil).GetSessionTTL), ctx, conversationID)
}

// GetSessionWithTTL mocks base method.
func (m *MockISessionRedisAcc) GetSessionWithTTL(ctx context.Context, conversationID string) (bool, int64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionWithTTL", ctx, conversationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetSessionWithTTL indicates an expected call of GetSessionWithTTL.
func (mr *MockISessionRedisAccMockRecorder) GetSessionWithTTL(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionWithTTL", reflect.TypeOf((*MockISessionRedisAcc)(nil).GetSessionWithTTL), ctx, conversationID)
}

// RefreshSession mocks base method.
func (m *MockISessionRedisAcc) RefreshSession(ctx context.Context, conversationID string, ttl int) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSession", ctx, conversationID, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshSession indicates an expected call of RefreshSession.
func (mr *MockISessionRedisAccMockRecorder) RefreshSession(ctx, conversationID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSession", reflect.TypeOf((*MockISessionRedisAcc)(nil).RefreshSession), ctx, conversationID, ttl)
}

// SetSession mocks base method.
func (m *MockISessionRedisAcc) SetSession(ctx context.Context, conversationID string, startTime int64, ttl int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSession", ctx, conversationID, startTime, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSession indicates an expected call of SetSession.
func (mr *MockISessionRedisAccMockRecorder) SetSession(ctx, conversationID, startTime, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSession", reflect.TypeOf((*MockISessionRedisAcc)(nil).SetSession), ctx, conversationID, startTime, ttl)
}
