# coding: utf-8
"""
行动类型创建测试用例
"""
import pytest
import allure
import json
from src.api.ontology.kn_action_type_api import ActionTypeApi
from src.common.read_data import data_reader
from src.common.global_var import global_vars
from test_case.ontology_base_test import BaseTest

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
positive_data = data_reader.read_yaml("ontology/action_type/action_create.yaml")

====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ontology

@allure.feature("知识网络行动类型管睆")
class TestActionTypeCreate(BaseTest):
    api = ActionTypeApi()
    box_id = global_vars.get_var("box_id")
    tool_id = global_vars.get_var("tool_id")
    parameters = global_vars.get_var("parameters")
    action_source = {"box_id": box_id, "tool_id": tool_id, "type": "tool"}

    @allure.story("删除行动类")
    @allure.title("删除")
    def test_delete_action_type(self, get_tool_id_parameters):
        self.api.create_action_type(
            kn_id=self.test_kn_id,
            name="test_delete",
            id="test_delete",
            action_type="add",
            object_type_id="person",
            affect_object_type_id="person",
            condition={
                "value_from": "const",
                "operation": "==",
                "field": "p_personid",
                "object_type_id": "person",
                "value": 94,
            },
            action_source=self.action_source,
            parameters=self.parameters,
        )

        # 删除行动类
        resp = self.api.delete_action_type(self.test_kn_id, "test_delete")

        self.assert_response_code(resp, 204)
        self.assert_db_record_not_exists(
            table=self.action__table,
            condition="f_id = %s and f_kn_id = %s",
            params=("test_delete", self.test_kn_id),
        )
