SHELL := /bin/bash

.PHONY: non-stream stream incremental-stream debug terminate resume all

non-stream:
	./non-stream.sh

stream:
	./stream.sh

incremental-stream:
	./incremental-stream.sh

debug:
	./debug.sh

terminate:
	./terminate.sh

resume:
	./resume.sh

all: non-stream stream incremental-stream debug
