// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/action_logs_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/action_logs_service.go -destination ../interfaces/mock/mock_action_logs_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-query/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActionLogsService is a mock of ActionLogsService interface.
type MockActionLogsService struct {
	ctrl     *gomock.Controller
	recorder *MockActionLogsServiceMockRecorder
	isgomock struct{}
}

// MockActionLogsServiceMockRecorder is the mock recorder for MockActionLogsService.
type MockActionLogsServiceMockRecorder struct {
	mock *MockActionLogsService
}

// NewMockActionLogsService creates a new mock instance.
func NewMockActionLogsService(ctrl *gomock.Controller) *MockActionLogsService {
	mock := &MockActionLogsService{ctrl: ctrl}
	mock.recorder = &MockActionLogsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionLogsService) EXPECT() *MockActionLogsServiceMockRecorder {
	return m.recorder
}

// CancelExecution mocks base method.
func (m *MockActionLogsService) CancelExecution(ctx context.Context, knID, execID, reason string) (*interfaces.CancelExecutionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExecution", ctx, knID, execID, reason)
	ret0, _ := ret[0].(*interfaces.CancelExecutionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelExecution indicates an expected call of CancelExecution.
func (mr *MockActionLogsServiceMockRecorder) CancelExecution(ctx, knID, execID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExecution", reflect.TypeOf((*MockActionLogsService)(nil).CancelExecution), ctx, knID, execID, reason)
}

// CreateExecution mocks base method.
func (m *MockActionLogsService) CreateExecution(ctx context.Context, exec *interfaces.ActionExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExecution", ctx, exec)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExecution indicates an expected call of CreateExecution.
func (mr *MockActionLogsServiceMockRecorder) CreateExecution(ctx, exec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExecution", reflect.TypeOf((*MockActionLogsService)(nil).CreateExecution), ctx, exec)
}

// GetExecution mocks base method.
func (m *MockActionLogsService) GetExecution(ctx context.Context, query *interfaces.ActionLogDetailQuery) (*interfaces.ActionExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecution", ctx, query)
	ret0, _ := ret[0].(*interfaces.ActionExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecution indicates an expected call of GetExecution.
func (mr *MockActionLogsServiceMockRecorder) GetExecution(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecution", reflect.TypeOf((*MockActionLogsService)(nil).GetExecution), ctx, query)
}

// QueryExecutions mocks base method.
func (m *MockActionLogsService) QueryExecutions(ctx context.Context, query *interfaces.ActionLogQuery) (*interfaces.ActionExecutionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExecutions", ctx, query)
	ret0, _ := ret[0].(*interfaces.ActionExecutionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExecutions indicates an expected call of QueryExecutions.
func (mr *MockActionLogsServiceMockRecorder) QueryExecutions(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExecutions", reflect.TypeOf((*MockActionLogsService)(nil).QueryExecutions), ctx, query)
}

// UpdateExecution mocks base method.
func (m *MockActionLogsService) UpdateExecution(ctx context.Context, knID, execID string, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExecution", ctx, knID, execID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExecution indicates an expected call of UpdateExecution.
func (mr *MockActionLogsServiceMockRecorder) UpdateExecution(ctx, knID, execID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExecution", reflect.TypeOf((*MockActionLogsService)(nil).UpdateExecution), ctx, knID, execID, updates)
}
