openapi: 3.0.2
info:
  title: Agent-Factory API
  version: 1.0.0
  description: |-
    API to access DIP

    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn
servers:
  - url: https://{host}:{port}/
    description: "host: 服务器IP, port: 默认端口443"
    variables:
      host:
        default: host
        description: 服务器IP
      port:
        default: "443"
        description: https默认端口443
security:
  - ApiKeyAuth: []
tags:
  - name: 公共Header说明
    description: |-
      # Authentication
      - 调用需要鉴权的API，必须将token放在HTTP header中："Authorization: Bearer ACCESS_TOKEN"

      # Business Domain
      - 业务域标识Header：`x-business-domain`，用于区分不同业务场景的请求
  - name: agent
  - name: 发布相关
  - name: 已发布
  - name: 最近访问
  - name: 产品
  - name: 个人空间（开发）
  - name: 模板
  - name: 权限
  - name: 工具结果处理策略
  - name: 其他
  - name: 对话管理
  - name: 对话session管理
  - name: 对话
  - name: 可观测性
  - name: 自定义错误码汇总
  - name: 相关文档
    description: |-
      相关文档：
      - [confluence](https://confluence.aishu.cn/pages/viewpage.action?pageId=261242083)
      - [devops](https://devops.aishu.cn/AISHUDevOps/DIP/_workitems/edit/744857)
x-tagGroups:
  - name: 通用说明
    tags:
      - 公共Header说明
  - name: Agent管理（V3）
    tags:
      - agent
      - 发布相关
      - 已发布
      - 最近访问
      - 产品
      - 个人空间（开发）
      - 模板
      - 权限
      - 工具结果处理策略
      - 其他
  - name: Agent运行（V1）
    tags:
      - 对话管理
      - 对话session管理
      - 对话
      - 可观测性
  - name: 错误码
    tags:
      - 自定义错误码汇总
  - name: 相关文档
    tags:
      - 相关文档
components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: HTTP Bearer token, formatted as `Bearer ACCESS_TOKEN`
  schemas:
    daenum.WritePublishToWhere:
      type: string
      enum:
        - square
    releasereq.UpdatePublishInfoReq:
      properties:
        category_ids:
          description: |
            - 非必填；为空时清空分类关联
            - 之前页面上分类是required，不过之前接口是非required。这里先和之前的接口保持一致。
        publish_to_where:
          description: |-
            - 发布到的目标
              - square: 发布到广场
            - 非必填；为空时不发布到任何目标
          items:
            $ref: '#/components/schemas/daenum.WritePublishToWhere'
        pms_control:
          description: |-
            - 权限控制信息
            - 非必填；为空时表示所有用户可见可用
        publish_to_bes:
          description: |-
            - 同时发布为其他类型
            - 非必填；为空时表示不额外发布为其他类型
paths:
  /api/agent-factory/v3/agent-market/agent/{agent_id}/version/{version}:
    get:
      security: []
  /api/agent-factory/v3/agent/{agent_id}/publish-info:
    get:
      security: []
    put:
      security: []
      requestBody:
        content:
          application/json:
            examples:
              example1:
                value:
                  category_ids:
                    - 01JRYRKP0M8VYHQSX4FXR5CKG2
                  description: 发布描述
            schema:
              $ref: "#/components/schemas/releasereq.UpdatePublishInfoReq"
  /api/agent-factory/v3/agent/{agent_id}/release-history:
    get:
      security: []
  /api/agent-factory/v3/category:
    get:
      security: []
  /api/agent-factory/v3/personal-space/agent-list:
    get:
      security: []
  /api/agent-factory/v3/published/agent-tpl/{tpl_id}:
    get:
      security: []
  /api/agent-factory/v3/recent-visit/agent:
    get:
      security: []
  /api/agent-factory/v3/agent-tpl/{id}/publish:
    post:
      security: []
  /api/agent-factory/v3/agent-tpl/{id}/publish-info:
    put:
      security: []
  /api/agent-factory/v3/agent-tpl/{id}/unpublish:
    put:
      security: []
  /api/agent-factory/v3/agent/{agent_id}/publish:
    post:
      security: []
      requestBody:
        content:
          application/json:
            examples:
              example1:
                value:
                  category_ids:
                    - 01JRYRKP0M8VYHQSX4FXR5CKG2
                  description: 发布描述
            schema:
              $ref: "#/components/schemas/releasereq.UpdatePublishInfoReq"
  /api/agent-factory/v3/published/agent:
    post:
      security: []
  /api/agent-factory/v3/published/agent-info-list:
    post:
      security: []
  /api/agent-factory/v3/agent/{agent_id}/unpublish:
    put:
      security: []
