SHELL := /bin/bash

.PHONY: chat multi-turn sessions history trace all

chat:
	./chat.sh

multi-turn:
	./multi-turn.sh

sessions:
	./sessions.sh

history:
	./history.sh

trace:
	./trace.sh

all: chat multi-turn sessions history trace
